CREATE TABLE IF NOT EXISTS records(id TEXT PRIMARY KEY,kind TEXT NOT NULL,data TEXT NOT NULL,version INTEGER NOT NULL DEFAULT 1,updated TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS records_kind ON records(kind);
CREATE TABLE IF NOT EXISTS metrics(campaign TEXT NOT NULL REFERENCES records(id),day TEXT NOT NULL,impressions INTEGER NOT NULL,clicks INTEGER NOT NULL,leads INTEGER NOT NULL,conversions INTEGER NOT NULL,spend_cents INTEGER NOT NULL,revenue_cents INTEGER NOT NULL,PRIMARY KEY(campaign,day));
CREATE TABLE IF NOT EXISTS assets(id TEXT PRIMARY KEY,name TEXT NOT NULL,mime TEXT NOT NULL,size INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS asset_chunks(asset TEXT NOT NULL REFERENCES assets(id),part INTEGER NOT NULL,body TEXT NOT NULL,PRIMARY KEY(asset,part));
CREATE TABLE IF NOT EXISTS activity(id INTEGER PRIMARY KEY,at TEXT NOT NULL,action TEXT NOT NULL,subject TEXT NOT NULL);
