const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>new Date().toLocaleDateString('en-CA'), money=n=>new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS'}).format(n/100), num=n=>new Intl.NumberFormat('es-AR',{maximumFractionDigits:2}).format(n);
let demoMode=false;
let token='',data={},view='overview',editing=null,kind='',pendingCSV='';
const fields={campaigns:[['name','Nombre'],['channel','Canal',['Meta Ads','Google Ads','LinkedIn','Email','Orgánico','Otro']],['objective','Objetivo',['Reconocimiento','Tráfico','Leads','Ventas']],['status','Estado',['Borrador','Activa','Pausada','Finalizada']],['owner','Responsable'],['start','Inicio','date'],['end','Fin','date'],['budget_cents','Presupuesto ARS','money'],['target_cpa_cents','CPA objetivo ARS (0: sin objetivo)','money'],['notes','Notas','textarea']],content:[['title','Título'],['campaign','Campaña','campaign'],['channel','Canal'],['format','Formato',['Imagen','Video','Carrusel','Texto','Email','Landing']],['status','Estado',['Idea','En producción','En revisión','Aprobado','Publicado']],['owner','Responsable'],['due','Fecha de publicación','date'],['copy','Texto de la pieza','textarea'],['url','Enlace HTTPS publicado','url']],tasks:[['title','Tarea'],['campaign','Campaña','campaign'],['owner','Responsable'],['partner','Agencia / proveedor / área'],['due','Vencimiento','date'],['priority','Prioridad',['Alta','Media','Baja']],['status','Estado',['Pendiente','En curso','Bloqueada','Hecha']],['notes','Notas','textarea']],ideas:[['title','Iniciativa'],['hypothesis','Hipótesis y criterio de éxito','textarea'],['owner','Responsable'],['impact','Impacto (1–5)','score'],['confidence','Confianza (1–5)','score'],['effort','Esfuerzo (1–5)','score'],['status','Estado',['Propuesta','En prueba','Adoptada','Descartada']],['result','Resultado del experimento','textarea']],metrics:[['campaign','Campaña','campaign'],['day','Fecha','date'],['impressions','Impresiones','number'],['clicks','Clics','number'],['leads','Leads','number'],['conversions','Conversiones','number'],['spend_cents','Inversión ARS','money'],['revenue_cents','Ingresos atribuidos ARS','money']]};
const titles={overview:['Cada acción, una dirección.','Panorama de resultados y próximos pasos.','Nueva campaña'],campaigns:['Campañas con propósito.','Presupuesto, objetivos y responsables en un solo lugar.','Nueva campaña'],content:['Contenido que avanza.','Agenda editorial y piezas. Registrá las publicaciones realizadas en cada canal.','Nuevo contenido'],tasks:['Un equipo, próximos pasos claros.','Coordinación con agencias, proveedores y áreas internas.','Nueva tarea'],metrics:['Resultados con contexto.','Datos manuales o CSV. Los indicadores se calculan sobre el período seleccionado.','Cargar métricas'],ideas:['La próxima mejora empieza acá.','Priorizá hipótesis y documentá lo aprendido.','Nueva iniciativa']};
async function api(path,options={}){if(demoMode)throw Error('El ejemplo es de solo lectura. Ingresá con tu clave para trabajar con datos reales.');const r=await fetch('/api/'+path,{...options,headers:{Authorization:'Bearer '+token,...(options.body&&typeof options.body==='string'?{'Content-Type':'application/json'}:{}),...options.headers}});if(!r.ok){let e;try{e=await r.json()}catch{e={detail:'No se pudo completar la operación.'}}throw Error(typeof e.detail==='string'?e.detail:JSON.stringify(e.detail))}return r}
async function refresh(){data=demoMode?await(await fetch('./demo.json')).json():await(await api('workspace')).json();const selected=$('#campaign-filter').value;$('#campaign-filter').innerHTML='<option value="">Todas las campañas</option>'+data.campaigns.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');$('#campaign-filter').value=selected;render()}
function notify(message){$('#status').textContent=message}
function selectedRows(){return data.metrics.filter(m=>(!$('#campaign-filter').value||m.campaign===$('#campaign-filter').value)&&m.day>=$('#from').value&&m.day<=$('#to').value)}
const totals=rows=>rows.reduce((a,m)=>{for(const k of ['impressions','clicks','leads','conversions','spend_cents','revenue_cents'])a[k]+=m[k];return a},{impressions:0,clicks:0,leads:0,conversions:0,spend_cents:0,revenue_cents:0});
const name=id=>data.campaigns.find(c=>c.id===id)?.name||'Sin campaña';
const badge=s=>`<span class="badge ${['Hecha','Publicado','Activa','Adoptada'].includes(s)?'good':['Bloqueada','Pausada'].includes(s)?'warn':''}">${esc(s)}</span>`;
const editButton=(k,id)=>`<button class="quiet" data-edit="${k}" data-id="${esc(id)}">Editar ↗</button>`;
const empty=()=>'<div class="empty"><strong>Un espacio listo para tus datos.</strong><p>Creá tu primer registro con el botón superior.</p></div>';
function kpis(t){return `<div class="kpis">${[['Inversión',money(t.spend_cents),'ARS · período seleccionado'],['Leads',num(t.leads),'Contactos reportados'],['Conversiones',num(t.conversions),'Eventos reportados'],['ROAS',t.spend_cents?num(t.revenue_cents/t.spend_cents)+'×':'—','Ingresos atribuidos / inversión']].map(([a,b,c])=>`<div class="kpi"><span>${a}</span><strong>${b}</strong><small>${c}</small></div>`).join('')}</div>`}
function render(){if($('#from').value>$('#to').value){notify('La fecha inicial no puede superar a la final.');return}const [title,sub,add]=titles[view];$('#title').textContent=title;$('#subtitle').textContent=sub;$('#add').textContent='+ '+add;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));const filter=$('#campaign-filter').value,t=totals(selectedRows());let html='';
if(view==='overview'){const alerts=[];for(const c of data.campaigns.filter(c=>!filter||c.id===filter)){const all=totals(data.metrics.filter(m=>m.campaign===c.id)),period=totals(selectedRows().filter(m=>m.campaign===c.id));if(all.spend_cents>c.budget_cents)alerts.push(`${c.name}: inversión acumulada ${money(all.spend_cents)} superior al presupuesto ${money(c.budget_cents)}. Revisá el gasto.`);if(c.target_cpa_cents&&period.conversions&&period.spend_cents/period.conversions>c.target_cpa_cents)alerts.push(`${c.name}: CPA ${money(period.spend_cents/period.conversions)} sobre objetivo ${money(c.target_cpa_cents)}. Revisá segmentación y piezas; este dato no prueba una causa.`);if(c.status==='Activa'&&!data.metrics.some(m=>m.campaign===c.id))alerts.push(`${c.name}: campaña activa sin resultados cargados.`)}html=kpis(t)+`<div class="grid"><section class="panel"><div class="panel-head"><h2>Señales para revisar</h2></div><div class="panel-body">${alerts.length?alerts.map(a=>`<div class="list-item"><p>${esc(a)}</p></div>`).join(''):'<p>No hay alertas con los datos disponibles. Esto no implica que las campañas estén optimizadas.</p>'}</div></section><section class="panel"><div class="panel-head"><h2>Próximos compromisos</h2></div><div class="panel-body">${data.tasks.filter(x=>x.status!=='Hecha'&&(!filter||x.campaign===filter)).sort((a,b)=>a.due.localeCompare(b.due)).slice(0,6).map(x=>`<div class="list-item"><h3>${esc(x.title)}</h3><p>${esc(x.owner)} · ${x.due} ${x.due<today()?'· Vencida':''}</p>${editButton('tasks',x.id)}</div>`).join('')||'<p>No hay tareas pendientes.</p>'}</div></section></div><section class="panel"><div class="panel-head"><h2>Actividad reciente</h2></div><div class="panel-body">${data.activity.slice(0,8).map(a=>`<p>${esc(a.action)} · ${esc(a.subject)} <small>${esc(new Date(a.at).toLocaleString('es-AR'))}</small></p>`).join('')||'<p>Los cambios aparecerán aquí.</p>'}</div></section>`}
if(view==='campaigns'){const rows=data.campaigns.filter(c=>!filter||c.id===filter);html=rows.length?'<div class="board">'+rows.map(c=>{const t=totals(data.metrics.filter(m=>m.campaign===c.id));return `<article class="card">${badge(c.status)}<h3>${esc(c.name)}</h3><p>${esc(c.channel)} · ${esc(c.objective)}</p><p>${esc(c.owner)} · ${c.start} → ${c.end}</p><div class="budget-line">${money(t.spend_cents)} / ${money(c.budget_cents)}</div><meter class="budget-bar" min="0" max="${Math.max(c.budget_cents,1)}" value="${t.spend_cents}"></meter><small>Inversión acumulada / presupuesto total</small><p>${esc(c.notes)}</p>${editButton('campaigns',c.id)}</article>`}).join('')+'</div>':empty()}
if(['content','tasks','ideas'].includes(view)){let rows=data[view].filter(r=>view==='ideas'||!filter||r.campaign===filter);rows.sort((a,b)=>view==='ideas'?b.impact*b.confidence/b.effort-a.impact*a.confidence/a.effort:a.due.localeCompare(b.due));html=rows.length?'<div class="board">'+rows.map(r=>`<article class="card">${badge(r.status)}<h3>${esc(r.title)}</h3><p>${esc(r.owner)} ${r.due?'· '+r.due:''}</p>${view==='ideas'?`<span class="score">${num(r.impact*r.confidence/r.effort)}</span><small>Impacto × confianza / esfuerzo</small><p>${esc(r.hypothesis)}</p><p>${esc(r.result)}</p>`:`<p>${esc(name(r.campaign))} · ${esc(r.channel||r.partner||'Equipo interno')}</p><p>${esc(r.copy||r.notes)}</p>${view==='tasks'?`<p>Prioridad ${esc(r.priority)} ${r.due<today()&&r.status!=='Hecha'?'· Vencida':''}</p>`:''}`}${r.url?`<p><a href="${esc(r.url)}" target="_blank" rel="noopener noreferrer">Ver publicación ↗</a></p>`:''}<div class="actions">${editButton(view,r.id)}${r.asset?`<button class="quiet" data-asset="${esc(r.asset)}">Descargar pieza ↓</button>`:''}</div></article>`).join('')+'</div>':empty()}
if(view==='metrics'){html=kpis(t)+`<section class="panel"><div class="panel-head"><h2>Indicadores del período</h2><div class="actions"><button class="quiet" id="import">Importar CSV ↑</button><button class="quiet" id="report">Reporte HTML ↓</button><button class="quiet" id="export">Exportar CSV ↓</button></div></div><div class="panel-body metric-help">CTR: ${t.impressions?num(t.clicks/t.impressions*100)+'%':'—'} · CPC: ${t.clicks?money(t.spend_cents/t.clicks):'—'} · CPL: ${t.leads?money(t.spend_cents/t.leads):'—'} · CPA: ${t.conversions?money(t.spend_cents/t.conversions):'—'}<p>Razones calculadas sobre las sumas del período. Los ingresos y conversiones son los que reportaste; no se deduplican entre plataformas.</p></div><div class="table-scroll"><table><thead><tr><th>Fecha / campaña</th><th>Impresiones</th><th>Clics</th><th>Leads</th><th>Conversiones</th><th>Inversión</th><th>Ingresos</th><th></th></tr></thead><tbody>${selectedRows().map(m=>`<tr><td>${m.day}<br>${esc(name(m.campaign))}</td>${['impressions','clicks','leads','conversions'].map(k=>`<td>${num(m[k])}</td>`).join('')}<td>${money(m.spend_cents)}</td><td>${money(m.revenue_cents)}</td><td>${editButton('metrics',m.campaign+'|'+m.day)}</td></tr>`).join('')}</tbody></table></div></section>`}
$('#view').innerHTML=html;document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openEditor(b.dataset.edit,b.dataset.id));document.querySelectorAll('[data-asset]').forEach(b=>b.onclick=()=>downloadAPI('assets/'+b.dataset.asset,data.assets.find(a=>a.id===b.dataset.asset)?.name||'pieza'));if(view==='metrics'){$('#import').onclick=()=>$('#import-dialog').showModal();$('#export').onclick=exportCSV;$('#report').onclick=report}}
function openEditor(k,id){if(demoMode){notify('Ejemplo de solo lectura. Ingresá con tu clave para crear o editar registros.');return}kind=k;editing=id?(k==='metrics'?data.metrics.find(m=>m.campaign+'|'+m.day===id):data[k].find(r=>r.id===id)):null;$('#edit-title').textContent=(editing?'Editar: ':'Crear: ')+titles[k][2];$('#edit-error').textContent=k==='metrics'?'Una carga para la misma campaña y fecha reemplaza los valores anteriores.':'';$('#fields').innerHTML=fields[k].map(([key,label,type])=>{const v=editing?.[key]??(type==='date'?today():type==='score'?3:['money','number'].includes(type)?0:'');let control;if(Array.isArray(type)||type==='campaign'){const opts=type==='campaign'?[...(k==='metrics'?[]:[['','Sin campaña']]),...data.campaigns.map(c=>[c.id,c.name])]:type.map(x=>[x,x]);control=`<select name="${key}" ${k==='metrics'?'required':''}>${opts.map(([a,b])=>`<option value="${esc(a)}" ${a===v?'selected':''}>${esc(b)}</option>`).join('')}</select>`}else if(type==='textarea')control=`<textarea name="${key}" rows="3" ${key==='hypothesis'?'required':''}>${esc(v)}</textarea>`;else control=`<input name="${key}" type="${['money','score','number'].includes(type)?'number':type||'text'}" value="${esc(type==='money'?v/100:v)}" ${['money','score','number'].includes(type)?`min="${type==='score'?1:0}" ${type==='score'?'max="5"':''} step="${type==='money'?'.01':'1'}"`:''} ${['url','partner'].includes(key)?'':'required'}>`;return `<label class="${type==='textarea'?'wide':''}">${label}${control}</label>`}).join('')+(k==='content'?'<label class="wide">Adjuntar o reemplazar pieza (PNG, JPG, WebP, PDF · 5 MB)<input name="file" type="file" accept="image/png,image/jpeg,image/webp,application/pdf"></label>':'');if(editing&&k==='metrics'){for(const n of ['campaign','day'])$(`#fields [name="${n}"]`).disabled=true}$('#editor').showModal()}
$('#edit-form').onsubmit=async e=>{e.preventDefault();$('#save').disabled=true;try{const body={};for(const [key,,type]of fields[kind]){const v=$(`#fields [name="${key}"]`).value;body[key]=type==='money'?Math.round(Number(v)*100):['number','score'].includes(type)?Number(v):v}if(kind==='content'){body.asset=editing?.asset||'';const file=$('#fields [name="file"]').files[0];if(file){if(file.size>5000000)throw Error('La pieza supera los 5 MB.');body.asset=(await(await api('assets?name='+encodeURIComponent(file.name),{method:'POST',body:file,headers:{'Content-Type':file.type}})).json()).id}}await api(kind==='metrics'?'metrics':'records/'+kind+(editing?'/'+editing.id+'?version='+editing.version:''),{method:kind==='metrics'||editing?'PUT':'POST',body:JSON.stringify(body)});$('#editor').close();await refresh();notify('Cambios guardados.')}catch(e){$('#edit-error').textContent=e.message}finally{$('#save').disabled=false}};
function download(blob,filename){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000)}
async function downloadAPI(path,filename){try{download(await(await api(path)).blob(),filename)}catch(e){notify(e.message)}}
const columns=['campaign','day','impressions','clicks','leads','conversions','spend_cents','revenue_cents'];
const csv=rows=>rows.map(r=>r.map(v=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"').join(',')).join('\r\n');
function exportCSV(){download(new Blob(['\ufeff'+csv([columns,...selectedRows().map(m=>columns.map(k=>m[k]))])],{type:'text/csv;charset=utf-8'}),'metricas.csv')}
function report(){const t=totals(selectedRows());const text=`<!doctype html><html lang="es"><meta charset="utf-8"><title>Reporte Marketing Desk</title><body><h1>Reporte de marketing digital</h1><p>${esc($('#from').value)} a ${esc($('#to').value)} · ${esc(filterName())}</p><p>Inversión: ${money(t.spend_cents)} · Ingresos atribuidos: ${money(t.revenue_cents)} · Leads: ${t.leads} · Conversiones: ${t.conversions}</p><p>CTR (clics / impresiones): ${t.impressions?num(t.clicks/t.impressions*100)+'%':'Sin datos'} · CPA (inversión / conversiones): ${t.conversions?money(t.spend_cents/t.conversions):'Sin datos'} · ROAS (ingresos / inversión): ${t.spend_cents?num(t.revenue_cents/t.spend_cents):'Sin datos'}</p><table border="1" cellpadding="8"><tr><th>Campaña</th><th>Inversión ARS</th><th>Leads</th><th>Conversiones</th><th>Ingresos ARS</th></tr>${data.campaigns.filter(c=>!$('#campaign-filter').value||c.id===$('#campaign-filter').value).map(c=>{const s=totals(selectedRows().filter(m=>m.campaign===c.id));return `<tr><td>${esc(c.name)}</td><td>${money(s.spend_cents)}</td><td>${s.leads}</td><td>${s.conversions}</td><td>${money(s.revenue_cents)}</td></tr>`}).join('')}</table><p>Fuente: carga manual e importación CSV. Sin deduplicación entre plataformas. Indicadores calculados sobre totales del período; no prueban causalidad. Generado ${esc(new Date().toLocaleString('es-AR'))}.</p></body></html>`;download(new Blob([text],{type:'text/html;charset=utf-8'}),'reporte-marketing.html')}
const filterName=()=>$('#campaign-filter').value?name($('#campaign-filter').value):'Todas las campañas';
$('#unlock').onsubmit=async e=>{e.preventDefault();demoMode=false;token=$('#key').value;try{await refresh();$('#login').hidden=true;$('#workspace').hidden=false;$('#key').value=''}catch(e){$('#login-error').textContent=e.message;token=''}};
$('#lock').onclick=()=>{demoMode=false;token='';data={};$('#view').replaceChildren();$('#workspace').hidden=true;$('#login').hidden=false};
$('#refresh').onclick=()=>refresh().catch(e=>notify(e.message));$('#backup').onclick=()=>downloadAPI('backup','marketing-desk-backup.sqlite3');
$('#nav').onclick=e=>{const b=e.target.closest('[data-view]');if(b){view=b.dataset.view;notify('');render()}};
$('#add').onclick=()=>openEditor(view==='overview'?'campaigns':view);document.querySelectorAll('.close').forEach(b=>b.onclick=()=>$('#editor').close());for(const id of ['from','to','campaign-filter'])$('#'+id).onchange=render;
$('#from').value=today().slice(0,8)+'01';$('#to').value=today();$('#close-import').onclick=()=>$('#import-dialog').close();
$('#csv-file').onchange=()=>{pendingCSV='';$('#confirm-import').hidden=true;$('#import-preview').textContent='';$('#import-status').textContent=''};
$('#template').onclick=()=>download(new Blob([csv([columns,...data.campaigns.map(c=>[c.id,today(),0,0,0,0,0,0])])],{type:'text/csv'}),'plantilla-metricas.csv');
$('#preview-import').onclick=async()=>{pendingCSV='';$('#confirm-import').hidden=true;try{const f=$('#csv-file').files[0];if(!f)throw Error('Seleccioná un archivo CSV.');if(f.size>2000000)throw Error('El CSV supera 2 MB.');const text=await f.text(),r=await(await api('import',{method:'POST',body:JSON.stringify({csv:text})})).json();pendingCSV=text;$('#import-status').textContent=`${r.rows} filas válidas · ${r.replaced} registros existentes se reemplazarían.`;$('#import-preview').textContent=JSON.stringify(r.preview,null,2);$('#confirm-import').hidden=false}catch(e){$('#import-status').textContent=e.message}};
$('#confirm-import').onclick=async()=>{if(!pendingCSV)return;$('#confirm-import').disabled=true;try{const r=await(await api('import',{method:'POST',body:JSON.stringify({csv:pendingCSV,confirm:true})})).json();pendingCSV='';$('#import-dialog').close();$('#confirm-import').hidden=true;await refresh();notify(`${r.rows} filas importadas.`)}catch(e){$('#import-status').textContent=e.message}finally{$('#confirm-import').disabled=false}};

$('#demo').onclick=async()=>{demoMode=true;token='';$('#from').value='2026-09-01';$('#to').value='2026-09-30';try{await refresh();$('#login').hidden=true;$('#workspace').hidden=false;notify('EJEMPLO · Datos ficticios · Solo lectura. Cerrá el espacio para ingresar con tu clave.')}catch(e){$('#login-error').textContent=e.message;demoMode=false}};
